
USE [master]
GO
/****** Object:  Database [MyStock]    Script Date: 6/6/2023 9:21:22 AM ******/
CREATE DATABASE [MyStock]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyStock', FILENAME = N'E:\prn211\project\FPTUniversity\MyStock\MyStock.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyStock_log', FILENAME = N'E:\prn211\project\FPTUniversity\MyStock\MyStock_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MyStock] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyStock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyStock] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyStock] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyStock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyStock] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyStock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyStock] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyStock] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyStock] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyStock] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyStock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyStock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyStock] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyStock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyStock] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyStock] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyStock] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyStock] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MyStock] SET  MULTI_USER 
GO
ALTER DATABASE [MyStock] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyStock] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyStock] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyStock] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyStock] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyStock] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MyStock] SET QUERY_STORE = OFF
GO
USE [MyStock]
GO
/****** Object:  Table [dbo].[Cars]    Script Date: 6/6/2023 9:21:22 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cars](
	[CarID] [int] NOT NULL,
	[CarName] [varchar](50) NOT NULL,
	[Manufacturer] [varchar](50) NOT NULL,
	[Price] [money] NOT NULL,
	[ReleasedYear] [int] NOT NULL,
 CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
(
	[CarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MyStock] SET  READ_WRITE 
GO
